name: Run tests and update docs
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn

      - name: Run eslint
        run: |
          yarn lint

      - name: Run tests
        run: |
          yarn test

      - name: Build the component
        run: |
          yarn build

  update-docs:
    name: Update documentation website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn

      - name: Build docs
        run: |
          yarn docs:build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs-dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
