name: Release NPM Package
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 7 * * 0-4'

env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  tests:
    uses: Nanopublication/nanopub-js/.github/workflows/build.yml@main
    secrets: inherit

  publish:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install package dependencies
      run: |
        corepack enable
        corepack prepare yarn@stable --activate
        yarn

    - name: Build
      run: yarn build

    - name: Publish NPM packages
      env:
        NPM_SECRET_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn publish -n $NPM_SECRET_TOKEN
